name: Dispatch to CI

on:
  push:
    branches:
      - main

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send repository_dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: resulknad/ps5-vps-setup
          event-type: image-builder-updated
          client-payload: '{"sha": "${{ github.sha }}"}'
